{
    'name': 'Gestion des recouvrements et des litiges: Personnalisé',
    'version': "19.0.1.0.0",
    'summary': 'Module de gestion des recouvrements et des litiges',
    'category': 'Accounting',
    'author': 'Baamtu',
    'maintainer': 'Baamtu',
    'website': 'http://www.baamtu.com',
    'license': 'LGPL-3',
    'depends': ['collection_disputes_base'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'data/sequence.xml',
        'views/collection_dispute_case_view.xml',
        'views/collateral_views.xml',
        'views/collateral_renewal_views.xml',
        'views/collateral_revaluation_views.xml',
        'views/customer.xml',
        'views/loan_settlement_statement_view.xml',
        'views/payment_incident_view.xml',
        'views/guarantor_view.xml',
        'views/transaction_agreement_views.xml',
    ],
    'assets': {},
    'demo': [],
    'qweb': [],
    'images': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
