from . import collection_base
from . import business_sector
from . import legal_status
from . import customer
from . import job
from . import justice_auxiliary
from . import tags
from . import collection_dispute_case
from . import collateral_type
from . import collateral_renewal
from . import collateral_reevaluation
from . import dunning_rule
from . import legal_dispute_type
from . import legal_dispute
from . import intervention_type
from . import justice_intervention
from . import transaction_agreement
from . import loan_settlement_statement
from . import additional_fee
from . import payment_nature
from . import negotiation_round
from . import amortization_line
from . import negotiation_limit_rule
from . import installment
from . import commission
from . import other_commission
from . import property_transfer
from . import constitutive_title
from . import judicial_decision
from . import judicial_decision_condemnation