{
    'name': 'Gestion des recouvrements et des litiges:Classique',
    'version': "19.0.1.0.0",
    'summary': 'Module de gestion des recouvrements et des litiges',
    'category': 'Accounting',
    'author': 'Baamtu',
    'maintainer': 'Baamtu',
    'website': 'http://www.baamtu.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'customisable_workflow_signature',
        'customisable_workflow_validation',
        'customisable_workflow_report', 'hr'],
    'data': [
        'data/customisable_workflow.workflow.xml',
        'data/sequence.xml',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/menu_views.xml',
        'views/tags_view.xml',
        'views/intervention_type_view.xml',
        'views/collection_dispute_case_view.xml',
        'views/collateral_type_views.xml',
        'views/collateral_renewal_views.xml',
        'views/collateral_revaluation_views.xml',
        'views/job.xml',
        'views/business_sector.xml',
        'views/legal_status.xml',
        # 'views/customer.xml',
        'views/justice_auxiliary.xml',
        'views/legal_dispute_type.xml',
        "views/legal_dispute_views.xml",
        'views/justice_intervention_view.xml',
        'views/loan_settlement_statement_view.xml',
        'views/additional_fee_menu.xml',
        'views/payment_nature_view.xml',
        'views/transaction_agreement_views.xml',
        'views/negotiation_limit_rule.xml',
        'views/negotiation_round_views.xml',
        'views/property_transfer.xml',
        'views/constitutive_title_view.xml',
        'views/res_currency_view.xml',
        'views/judicial_decision_view.xml',
        'views/amortization_line_view.xml'
    ],
    'assets': {
    },
    'demo': [],
    'qweb': [],
    'images': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
